services:
  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  worker:
    build: .
    command: celery -A app.celery_app worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app
    
  beat:
    build: .
    command: celery -A app.celery_app beat --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app
  
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: uptime_monitor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  migrations:
    build: .
    command: alembic upgrade head
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      DATABASE_URL: postgresql+psycopg2://user:password@db:5432/uptime_monito

volumes:
  postgres_data: