"""create target table

Revision ID: 04560d0d6827
Revises: 215c95a99ca9
Create Date: 2026-03-13 23:37:52.025079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04560d0d6827'
down_revision: Union[str, Sequence[str], None] = '215c95a99ca9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('targets', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('targets', 'name')
    # ### end Alembic commands ###
