"""add owner to targets

Revision ID: b126834dccf8
Revises: e1587e95df6e
Create Date: 2026-03-17 16:39:32.390960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b126834dccf8'
down_revision: Union[str, Sequence[str], None] = 'e1587e95df6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('targets', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'targets', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'targets', type_='foreignkey')
    op.drop_column('targets', 'owner_id')
    # ### end Alembic commands ###
